### ISSUE TITLE
invoking generator for vue-cli-plugin-vue-next..

### ISSUE THREAD

**Issue by yangdan8** [vuejs/vue-cli-plugin-vue-next#12]
vue add vue-add后直接报错

**Comment by sodatea** [comment]
报什么错？

**Comment by yangdan8** [comment]
Error: EPERM: operation not permitted, lstat 'C:\WINDOWS\system32\LogFiles\WMI\RtBackup'

**Comment by sodatea** [comment]
不太像是这个插件的报错。

`vue add` 其他插件会报这个错吗？
有没有更完整一点的报错日志？

**Comment by yangdan8** [comment]
�  Installing vue-cli-plugin-vue-next...

yarn add v1.22.4
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Saved lockfile.
success Saved 16 new dependencies.
info Direct dependencies
└─ vue-cli-plugin-vue-next@0.0.4
info All dependencies
├─ @types/color-name@1.1.1
├─ ansi-styles@4.2.1
├─ big.js@5.2.2
├─ chalk@3.0.0
├─ color-convert@2.0.1
├─ color-name@1.1.4
├─ emojis-list@3.0.0
├─ has-flag@4.0.0
├─ hash-sum@2.0.0
├─ json5@1.0.1
├─ loader-utils@1.4.0
├─ merge-source-map@1.1.0
├─ minimist@1.2.5
├─ supports-color@7.1.0
├─ vue-cli-plugin-vue-next@0.0.4
└─ vue-loader@16.0.0-alpha.3
Done in 1.27s.
✔  Successfully installed plugin: vue-cli-plugin-vue-next


�  Invoking generator for vue-cli-plugin-vue-next...
 ERROR  TypeError: Received an unexpected value [object Undefined]
TypeError: Received an unexpected value [object Undefined]
    at fromAST (C:\Users\adminxxx\AppData\Roaming\nvm\v12.16.1\node_modules\@vue\cli\node_modules\_jscodeshift@0.7.0@jscode
shift\src\core.js:70:9)
    at core (C:\Users\adminxxx\AppData\Roaming\nvm\v12.16.1\node_modules\@vue\cli\node_modules\_jscodeshift@0.7.0@jscodeshi
ft\src\core.js:45:5)
    at module.exports (E:\vuenext-test\node_modules\vue-cli-plugin-vue-next\generator\codemods\rfc09-global-api\index.js
:6:16)
    at newTransform (C:\Users\adminxxx\AppData\Roaming\nvm\v12.16.1\node_modules\@vue\cli\node_modules\_vue-jscodeshift-ada
pter@2.0.3@vue-jscodeshift-adapter\src\jscodeshift-mode.js:9:14)
    at runCodemod (C:\Users\adminxxx\AppData\Roaming\nvm\v12.16.1\node_modules\@vue\cli\lib\util\runCodemod.js:29:26)
    at C:\Users\adminxxx\AppData\Roaming\nvm\v12.16.1\node_modules\@vue\cli\lib\GeneratorAPI.js:377:21
    at Generator.resolveFiles (C:\Users\adminxxx\AppData\Roaming\nvm\v12.16.1\node_modules\@vue\cli\lib\Generator.js:268:13
)
    at Generator.generate (C:\Users\adminxxx\AppData\Roaming\nvm\v12.16.1\node_modules\@vue\cli\lib\Generator.js:175:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runGenerator (C:\Users\adminxxx\AppData\Roaming\nvm\v12.16.1\node_modules\@vue\cli\lib\invoke.js:109:3)
PS E:\vuenext-test> vue add vue-next 1.txt
PS E:\vuenext-test> vue add vue-next > 1.txt
 ERROR  TypeError: Received an unexpected value [object Undefined]
TypeError: Received an unexpected value [object Undefined]
    at fromAST (C:\Users\adminxxx\AppData\Roaming\nvm\v12.16.1\node_modules\@vue\cli\node_modules\_jscodeshift@0.7.0@jscode
shift\src\core.js:70:9)
    at core (C:\Users\adminxxx\AppData\Roaming\nvm\v12.16.1\node_modules\@vue\cli\node_modules\_jscodeshift@0.7.0@jscodeshi
ft\src\core.js:45:5)
    at module.exports (E:\vuenext-test\node_modules\vue-cli-plugin-vue-next\generator\codemods\rfc09-global-api\index.js
:6:16)
    at newTransform (C:\Users\adminxxx\AppData\Roaming\nvm\v12.16.1\node_modules\@vue\cli\node_modules\_vue-jscodeshift-ada
pter@2.0.3@vue-jscodeshift-adapter\src\jscodeshift-mode.js:9:14)
    at runCodemod (C:\Users\adminxxx\AppData\Roaming\nvm\v12.16.1\node_modules\@vue\cli\lib\util\runCodemod.js:29:26)
    at C:\Users\adminxxx\AppData\Roaming\nvm\v12.16.1\node_modules\@vue\cli\lib\GeneratorAPI.js:377:21
    at Generator.resolveFiles (C:\Users\adminxxx\AppData\Roaming\nvm\v12.16.1\node_modules\@vue\cli\lib\Generator.js:268:13
)
    at Generator.generate (C:\Users\adminxxx\AppData\Roaming\nvm\v12.16.1\node_modules\@vue\cli\lib\Generator.js:175:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runGenerator (C:\Users\adminxxx\AppData\Roaming\nvm\v12.16.1\node_modules\@vue\cli\lib\invoke.js:109:3)

**Comment by yangdan8** [comment]
修改C:\WINDOWS\system32\LogFiles权限为everyone后报这个错

**Comment by sodatea** [comment]
这个错是 `src/main.js` 解析出错。可能原因：
1. 这个文件不存在；
2. 这个文件里用了非标准的 JS 语法。

如果是 1 的话请新建一个空的 `src/index.js`，然后自行修改剩余的不符合 Vue 3 API 的代码。我们的插件没办法考虑到所有可能情况，所以不一定能正确处理所有的 API 变更。不过针对这个问题接下来准备加个 try catch 防止这个报错影响插件使用。
如果是 2 的话还烦请提供一下文件内容。

**Comment by yangdan8** [comment]
都不是,是因为我用的typescript的原因?

**Comment by sodatea** [comment]
那应该是的……现在还没做 TS 的测试，可能没法用

**Comment by yangdan8** [comment]
找打原因了,确实是因为文件改名了

**Comment by yangdan8** [comment]
typescript下依然是不能正常使用的,都跑不起来
