### ISSUE TITLE
Error on invoking generator

### ISSUE THREAD

**Issue by Kunoacc** [vuejs/vue-cli-plugin-vue-next#13]
ERROR  TypeError: Cannot read property 'match' of null
TypeError: Cannot read property 'match' of null
    at resolveDeps (C:\Users\nelson.atuonwu\AppData\Local\Yarn\Data\global\node_modules\@vue\cli\lib\util\mergeDeps.js:15:27)
    at GeneratorAPI.extendPackage (C:\Users\nelson.atuonwu\AppData\Local\Yarn\Data\global\node_modules\@vue\cli\lib\GeneratorAPI.js:196:20)
    at module.exports (C:\Users\nelson.atuonwu\Sources\JS\Vue\howfast-next\node_modules\vue-cli-plugin-vue-next\generator\index.js:5:7)
    at Generator.initPlugins (C:\Users\nelson.atuonwu\AppData\Local\Yarn\Data\global\node_modules\@vue\cli\lib\Generator.js:143:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Generator.generate (C:\Users\nelson.atuonwu\AppData\Local\Yarn\Data\global\node_modules\@vue\cli\lib\Generator.js:161:5)
    at async runGenerator (C:\Users\nelson.atuonwu\AppData\Local\Yarn\Data\global\node_modules\@vue\cli\lib\invoke.js:120:3)
    at async invoke (C:\Users\nelson.atuonwu\AppData\Local\Yarn\Data\global\node_modules\@vue\cli\lib\invoke.js:101:3)

**Comment by Tzahile** [comment]
Looks like after adding this plugin, every other plugin's generator fails (`vuex`, `vue-router`, even `vuetify`). 

The opposite happens as well - after setting a project with all of those mentioned, generator of vue-next plugin fails

**Comment by Kunoacc** [comment]
Any ideas on how to bypass this?

**Comment by sodatea** [comment]
Please upgrade your global `@vue/cli` version.

According to the error log, the version you used is somehow outdated and does not support pruning unused dependencies in the generator call, which is a required feature of this particular plugin.
