### ISSUE TITLE
 TypeError: Cannot read property 'match' of null

### ISSUE THREAD

**Issue by wangjieCode** [vuejs/vue-cli-plugin-vue-next#16]
Error reporting of installing Vue next

node version 12.14.0

**Comment by sodatea** [comment]
请提供一下可以复现的项目代码

**Comment by ZhengXiaowei** [comment]
直接在已有的vue项目里执行`vue add vue-next`就会报match这个错误：
```
 ERROR  TypeError: Cannot read property 'match' of null
TypeError: Cannot read property 'match' of null
    at resolveDeps (/usr/local/lib/node_modules/@vue/cli/lib/util/mergeDeps.js:10:27)
    at GeneratorAPI.extendPackage (/usr/local/lib/node_modules/@vue/cli/lib/GeneratorAPI.js:134:20)
    at module.exports (/Users/xiao/Desktop/vue3/vue3_demo/node_modules/vue-cli-plugin-vue-next/generator/index.js:5:7)
    at /usr/local/lib/node_modules/@vue/cli/lib/Generator.js:103:7
    at Array.forEach (<anonymous>)
    at new Generator (/usr/local/lib/node_modules/@vue/cli/lib/Generator.js:101:13)
    at runGenerator (/usr/local/lib/node_modules/@vue/cli/lib/invoke.js:123:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async invoke (/usr/local/lib/node_modules/@vue/cli/lib/invoke.js:117:3)
```

**Comment by wangjieCode** [comment]
> 请提供一下可以复现的项目代码

https://github.com/wangjieCode/-TypeError-Cannot-read-property-match-of-null/tree/master

**Comment by sodatea** [comment]
全局安装的 `@vue/cli` 版本太老了，请升级到 4.3.1
