### ISSUE TITLE
安装成功后，接下来的步骤报错

### ISSUE THREAD

**Issue by sufangyu** [vuejs/vue-cli-plugin-vue-next#23]
```
PS D:\labs\vue\vue-next-test> vue add vue-next

📦  Installing vue-cli-plugin-vue-next...

+ vue-cli-plugin-vue-next@0.1.2
added 9 packages from 40 contributors in 23.229s
✔  Successfully installed plugin: vue-cli-plugin-vue-next

 ERROR  TypeError: Cannot read property 'match' of null
TypeError: Cannot read property 'match' of null
    at resolveDeps (C:\Users\Yu\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\mergeDeps.js:10:27)
    at GeneratorAPI.extendPackage (C:\Users\Yu\AppData\Roaming\npm\node_modules\@vue\cli\lib\GeneratorAPI.js:134:20)
    at module.exports (D:\labs\vue\vue-next-test\node_modules\vue-cli-plugin-vue-next\generator\index.js:5:7)
    at Generator.plugins.forEach (C:\Users\Yu\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:103:7)
    at Array.forEach (<anonymous>)
    at new Generator (C:\Users\Yu\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:101:13)
    at runGenerator (C:\Users\Yu\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:116:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by sufangyu** [comment]
升级 cli 为 4.x 可以了
