### ISSUE TITLE
 ERROR  TypeError: Cannot read property 'match' of null

### ISSUE THREAD

**Issue by devemloop** [vuejs/vue-cli-plugin-vue-next#27]
🚀  `Ivoking generator for vue-cli-plugin-vue-next...
 ERROR  TypeError: Cannot read property 'match' of null
TypeError: Cannot read property 'match' of null
    at resolveDeps (C:\Users\marro\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\mergeDeps.js:15:27)
    at GeneratorAPI.extendPackage (C:\Users\marro\AppData\Roaming\npm\node_modules\@vue\cli\lib\GeneratorAPI.js:196:20)
    at module.exports (E:\PARA ORDENAR\EDesarrollo\proyectos\hakuneko-vue\node_modules\vue-cli-plugin-vue-next\generator\index.js:5:7)
    at Generator.initPlugins (C:\Users\marro\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:143:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Generator.generate (C:\Users\marro\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:161:5)
    at async runGenerator (C:\Users\marro\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:120:3)
    at async invoke (C:\Users\marro\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:101:3)`

**Comment by mtgr1020** [comment]
The same problem occurred when I used Vue CLI v3.12.1,Available when I upgrade to v4.3.1

**Comment by sodatea** [comment]
Please use the latest version of @vue/cli
