### ISSUE TITLE
SyntaxError: Only declares and type imports are allowed inside declare module

### ISSUE THREAD

**Issue by bobmoff** [vuejs/vue-cli-plugin-vue-next#33]
I get this error when trying to install the plugin

```js
SyntaxError: Only declares and type imports are allowed inside declare module (34:4)
    at Object._raise (/usr/local/lib/node_modules/@vue/cli/node_modules/@babel/parser/lib/index.js:742:17)
    at Object.raiseWithData (/usr/local/lib/node_modules/@vue/cli/node_modules/@babel/parser/lib/index.js:735:17)
    at Object.raise (/usr/local/lib/node_modules/@vue/cli/node_modules/@babel/parser/lib/index.js:729:17)
    at Object.unexpected (/usr/local/lib/node_modules/@vue/cli/node_modules/@babel/parser/lib/index.js:8779:16)
    at Object.expectContextual (/usr/local/lib/node_modules/@vue/cli/node_modules/@babel/parser/lib/index.js:8745:41)
    at Object.flowParseDeclareModule (/usr/local/lib/node_modules/@vue/cli/node_modules/@babel/parser/lib/index.js:1457:14)
    at Object.flowParseDeclare (/usr/local/lib/node_modules/@vue/cli/node_modules/@babel/parser/lib/index.js:1409:21)
    at Object.parseExpressionStatement (/usr/local/lib/node_modules/@vue/cli/node_modules/@babel/parser/lib/index.js:2558:23)
    at Object.parseStatementContent (/usr/local/lib/node_modules/@vue/cli/node_modules/@babel/parser/lib/index.js:11238:19)
    at Object.parseStatement (/usr/local/lib/node_modules/@vue/cli/node_modules/@babel/parser/lib/index.js:11104:17)
```

Not sure where to look for any solution.

**Comment by bobmoff** [comment]
Wops.

I had this in the main.ts file

```js
declare module '@vue/composition-api/dist/component/component' {
     interface SetupContext {
         readonly refs: { [key: string]: Vue | Element | Vue[] | Element[] }
     }
 }
```
