### ISSUE TITLE
TypeError: api.assertCliVersion is not a function

### ISSUE THREAD

**Issue by olearycrew** [vuejs/vue-cli-plugin-vue-next#38]
When running `vue add vue-next` I got the following error:

```
✨  Done in 2.16s.
✔  Successfully installed plugin: vue-cli-plugin-vue-next

 ERROR  TypeError: api.assertCliVersion is not a function
TypeError: api.assertCliVersion is not a function
    at module.exports (/Users/brendan/repos/demos/teamcheck/node_modules/vue-cli-plugin-vue-next/generator/index.js:6:7)
    at /usr/local/lib/node_modules/@vue/cli/lib/Generator.js:103:7
    at Array.forEach (<anonymous>)
    at new Generator (/usr/local/lib/node_modules/@vue/cli/lib/Generator.js:101:13)
    at runGenerator (/usr/local/lib/node_modules/@vue/cli/lib/invoke.js:123:21)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async invoke (/usr/local/lib/node_modules/@vue/cli/lib/invoke.js:117:3)
```

**Comment by fangbinwei** [comment]
maybe you should update you @vue/cli
